---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: weavego
  labels:
    name: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: hello-world
